### ISSUE TITLE
request video demo

### ISSUE THREAD

**Issue by glocke01** [AlliewayAudio/AlliewayAudio_Series_I#1]
Hi, 

I saw your modules on the library. I'm just writing to let you know that it would encourage me to purchase if you were to post some patch examples on YT. Even better would be some voice over describing the patch, but patch notes in the description would go a long way toward helping me understand what I'm buying.

The PDF owner's guides look v. cool.

**Comment by AlliewayAudio** [comment]
Heya, thanks for the comment - indepth videos for each module are on the way, should be out soon! My youtube is https://www.youtube.com/channel/UCeo2Fo1OidWpT83BT5xmCZw - stay tuned :D

**Comment by glocke01** [comment]
awesome, thanks!
